# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakery',
            name='pub_date',
        ),
    ]
