# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_remove_bakery_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(default='SOME STRING', max_length=20)),
                ('name', models.CharField(default='SOME STRING', max_length=20)),
                ('email', models.EmailField(default='SOME STRING', max_length=254)),
                ('type', models.CharField(default='SOME STRING', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SOME STRING', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HasProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bakery_id', models.IntegerField(default=0)),
                ('product_id', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Logging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField(default=0)),
                ('account', models.CharField(default='SOME STRING', max_length=50)),
                ('event_text', models.CharField(default='SOME STRING', max_length=500)),
                ('kind', models.CharField(default='SOME STRING', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(default=0)),
                ('bakery_id', models.IntegerField(default=0)),
                ('status', models.CharField(default='SOME STRING', max_length=10)),
                ('time_pickup', models.DateTimeField()),
                ('time_ordered', models.DateTimeField()),
                ('comment', models.CharField(default='SOME STRING', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SOME STRING', max_length=50)),
                ('foto_id', models.IntegerField(default=0)),
                ('category_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=0)),
                ('product_id', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='bakery',
            name='country',
        ),
        migrations.AddField(
            model_name='bakery',
            name='adress',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='bakery',
            name='bestelLimitTime',
            field=models.CharField(default='SOME STRING', max_length=10),
        ),
        migrations.AddField(
            model_name='bakery',
            name='description',
            field=models.CharField(default='SOME STRING', max_length=300),
        ),
        migrations.AddField(
            model_name='bakery',
            name='email',
            field=models.EmailField(default='SOME STRING', max_length=254),
        ),
        migrations.AddField(
            model_name='bakery',
            name='foto_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bakery',
            name='openingsuren',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='bakery',
            name='telephone',
            field=models.CharField(default='SOME STRING', max_length=11),
        ),
        migrations.AlterField(
            model_name='bakery',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
