# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_auto_20160303_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakery',
            name='website',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AlterField(
            model_name='bakery',
            name='telephone',
            field=models.CharField(default='SOME STRING', max_length=12),
        ),
    ]
