# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_auto_20160303_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SOME STRING', max_length=100)),
                ('link', models.CharField(default='SOME STRING', max_length=100)),
                ('description', models.CharField(default='SOME STRING', max_length=200)),
            ],
        ),
    ]
