# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='surname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='bakery',
            name='adress',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bakery',
            name='bestelLimitTime',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='bakery',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='bakery',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='bakery',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bakery',
            name='openings',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bakery',
            name='telephone',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='bakery',
            name='website',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='foto',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='foto',
            name='link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='foto',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='logging',
            name='account',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='logging',
            name='event_text',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='logging',
            name='kind',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
