# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0013_bakery_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakery',
            name='client',
            field=models.IntegerField(default=0),
        ),
    ]
