# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0014_bakery_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foto',
        ),
        migrations.RenameField(
            model_name='bakery',
            old_name='client',
            new_name='member',
        ),
        migrations.RemoveField(
            model_name='bakery',
            name='foto_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='foto_id',
        ),
        migrations.AddField(
            model_name='bakery',
            name='foto_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='foto_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
