# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-25 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0016_auto_20160425_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasproduct',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='totalPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product_order',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
