# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-08 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0021_account_salt'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdyenPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('shipDate', models.DateTimeField()),
                ('account_id', models.IntegerField(default=0)),
                ('bakery_id', models.IntegerField(default=0)),
                ('clientPay', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('transactionCosts', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('succes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PointPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('shipDate', models.DateTimeField()),
                ('account_id', models.IntegerField(default=0)),
                ('bakery_id', models.IntegerField(default=0)),
                ('clientPay', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('succes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='language',
            field=models.CharField(default='nl', max_length=200),
        ),
        migrations.AddField(
            model_name='account',
            name='recurringContract',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='shopperReference',
            field=models.CharField(default='', max_length=100),
        ),
    ]
