# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-12 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0023_account_lastorderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='recurringContract',
        ),
    ]
