# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-14 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0024_remove_account_recurringcontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='adyenpayment',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pointpayment',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
    ]
