# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-14 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0027_auto_20160514_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adyenpayment',
            old_name='bakery_id',
            new_name='bakeryId',
        ),
        migrations.RenameField(
            model_name='hasproduct',
            old_name='bakery_id',
            new_name='bakeryId',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='bakery_id',
            new_name='bakeryId',
        ),
        migrations.RenameField(
            model_name='pointpayment',
            old_name='bakery_id',
            new_name='bakeryId',
        ),
    ]
