# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-14 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0028_auto_20160514_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adyenpayment',
            old_name='account_id',
            new_name='accountId',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='account_id',
            new_name='accountId',
        ),
        migrations.RenameField(
            model_name='pointpayment',
            old_name='account_id',
            new_name='accountId',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='account_id',
            new_name='accountId',
        ),
    ]
