# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-14 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0031_auto_20160514_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='time_pickup',
            new_name='timePickup',
        ),
    ]
