# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-14 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0033_auto_20160514_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='adyenpayment',
            name='extraCredit',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
    ]
